### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Jip-Hop** [Pithikos/python-rectangles#2]
When doing `print(Rect(8.439482924217852, 76.08515847648438, 35.836311819999686, 1).distance_to_rect(Rect(0, 50, 1436, 41)))` I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "geometry.py", line 191, in distance_to_rect
    assert edge2
AssertionError
```
Is this the same issue as the closed issue #1 ?

**Comment by Jip-Hop** [comment]
Also with:
```
rect1=Rect(12.033261954622033, 8.427587347073734, 1, 1)
rect2=Rect(10.171466360158082, 8.884201162003432, 6.1721591535324585, 1)
print(rect1.distance_to_rect(rect2))
```
If I get it right that should correspond to this:
<img width="501" alt="schermafbeelding 2017-05-19 om 19 15 14" src="https://cloud.githubusercontent.com/assets/2871973/26259048/89ac1248-3cc7-11e7-9f1a-fecec38d57a7.png">
So distance should be 0.
Am I doing something wrong?

**Comment by Pithikos** [comment]
You are using the library correctly. The way of calculating the distance is missing some edge cases (probably including yours). I didn't have time to work on this. The way the distance is calculated should probably be changed to something more robust!

**Comment by Pithikos** [comment]
I think I rushed to answer that. I had a look and this might be totally unrelated to the closed issue.

The problem was actually n the `overlaps_with` - checking if a rectangle is overlapping with another rectangle. Apparently the function was only checking for one rectangle and thus missing some cases. Since the distance is using this function it couldn't work properly.

I fixed this now with 3dcee1786b876117674c0a1371b0a0f1d5fc313f and added a regression test.

**Comment by Pithikos** [comment]
@

**Comment by Jip-Hop** [comment]
Thanks for fixing this! From a brief test with my data I can confirm it no longer crashes :) But are there still some edge cases missing when calculating the distance? If so I might need to look for another code snippet or library to reliably calculate this distance.

**Comment by Pithikos** [comment]
It is hard to say. There is a lot of test coverage for general cases. However I never managed to find some already calculated distances to test against.
